config_train:
  data: "./dataset/yolo_config.yaml"
  epochs: 10
  batch: 32
  imgsz: 640
  device: "cuda"
  workers: 8
  optimizer: "auto"
  lr0: 0.01
  patience: 50
  seed: 4
  mosaic: 0
  close_mosaic: 0